// This file is generated by Slice Machine. Update with care!

import { SliceZoneComponents } from '@prismicio/react'
import CallToAction from './CallToAction'
import FullWidthImage from './FullWidthImage'
import Header from './Header'
import Herosection from './Herosection'
import ImageGallery from './ImageGallery'
import LinkImageGallery from './LinkImageGallery'
import Menu from './Menu'
import Quote from './Quote'
import TextContent from './TextContent'

export {
  CallToAction,
  FullWidthImage,
  Header,
  Herosection,
  ImageGallery,
  LinkImageGallery,
  Menu,
  Quote,
  TextContent,
}

export const components = {
  call_to_action: CallToAction,
  full_width_image: FullWidthImage,
  header: Header,
  herosection: Herosection,
  image_gallery: ImageGallery,
  link_image_gallery: LinkImageGallery,
  menu: Menu,
  quote: Quote,
  text_content: TextContent,
}
