// Code generated by Slice Machine. DO NOT EDIT.

import CallToAction from './CallToAction';
import Form from './Form';
import FullWidthImage from './FullWidthImage';
import Header from './Header';
import Herosection from './Herosection';
import ImageGallery from './ImageGallery';
import LinkImageGallery from './LinkImageGallery';
import Menu from './Menu';
import Quote from './Quote';
import References from './References';
import TextContent from './TextContent';

export {
	CallToAction,
	Form,
	FullWidthImage,
	Header,
	Herosection,
	ImageGallery,
	LinkImageGallery,
	Menu,
	Quote,
	References,
	TextContent,
};

export const components = {
	call_to_action: CallToAction,
	form: Form,
	full_width_image: FullWidthImage,
	header: Header,
	herosection: Herosection,
	image_gallery: ImageGallery,
	link_image_gallery: LinkImageGallery,
	menu: Menu,
	quote: Quote,
	references: References,
	text_content: TextContent,
};
