import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import * as prismic from '@prismicio/client'
import { Footer } from '../../components/footer'
import { createClient } from '../../prismicio'
import { Slicemachine } from '../../components/slicemachine'
import { Header } from '../../components/header'

export const getStaticProps: GetStaticProps = async ({
  params,
  previewData,
}) => {
  const type = 'what-you-can-do-subpage'

  const client = createClient(previewData)
  // @ts-ignore
  const document = (await client.getByUID(type, params?.uid, {})) || null
  const footer = (await client.getSingle('footer', {})) || null
  const menu = (await client.getSingle('burgerMenu', {})) || null

  return {
    props: {
      document,
      footer,
      menu,
    },
  }
}

export async function getStaticPaths() {
  const client = createClient()
  const docs = await client.get({
    predicates: prismic.predicate.at(
      'document.type',
      'what-you-can-do-subpage'
    ),
    lang: '*',
  })

  return {
    paths: docs.results.map((doc) => {
      return { params: { uid: doc.uid } }
    }),
    fallback: false,
  }
}

interface Props {
  document: any
  footer: any
  menu: any
}

const WhatYouCanDo: NextPage<Props> = (props) => {
  return (
    <>
      <Head>
        <title>Aerosol Aliance</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
      </Head>
      <main className="flex relative flex-col mx-auto max-w-[1920px]">
        <Header slices={props.menu?.data?.slices} />
        <Slicemachine slices={props.document?.data?.slices} />
      </main>
      <Footer data={props.footer.data} />
    </>
  )
}

export default WhatYouCanDo
