import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import { Footer } from '../../components/footer'
import { createClient } from '../../prismicio'
import { Header } from '../../components/header'
import { SliceZone } from '@prismicio/react'
import { components } from '../../slices'

export const getStaticProps: GetStaticProps = async ({ previewData }) => {
  const client = createClient(previewData)

  const whatYouCanDo = (await client.getSingle('what-you-can-do', {})) || null
  const footer = (await client.getSingle('footer', {})) || null
  const menu = (await client.getSingle('burgerMenu', {})) || null

  return {
    props: {
      whatYouCanDo,
      footer,
      menu,
    },
  }
}

interface Props {
  whatYouCanDo: any
  footer: any
  menu: any
}

const WhatYouCanDo: NextPage<Props> = (props) => {
  const { footer } = props
  return (
    <>
      <Head>
        <title>Aerosol Aliance</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
      </Head>
      <main className="relative mx-auto flex max-w-[1920px] flex-col">
        <Header slices={props.menu?.data?.slices} />
        <SliceZone
          slices={props.whatYouCanDo?.data?.slices}
          components={components}
        />
      </main>
      <Footer {...footer} />
    </>
  )
}

export default WhatYouCanDo
