import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import { Footer } from '../components/footer'
import { createClient } from '../prismicio'
import { Header } from '../components/header'
import * as prismic from '@prismicio/client'
import { SliceZone } from '@prismicio/react'
import { components } from '../slices'

export async function getStaticPaths() {
  const client = createClient()
  const docs = await client.get({
    predicates: prismic.predicate.at('document.type', 'content-page'),
    lang: '*',
  })
  return {
    paths: docs.results.map((doc: any) => {
      return {
        params: {
          uid: doc.uid,
        },
      }
    }),
    fallback: false,
  }
}

export const getStaticProps: GetStaticProps = async ({
  params,
  previewData,
}) => {
  const client = createClient(previewData)

  // @ts-ignore
  const doc = (await client.getByUID('content-page', params?.uid, {})) || null
  const footer = (await client.getSingle('footer', {})) || null
  const menu = (await client.getSingle('burgerMenu', {})) || null

  return {
    props: {
      doc,
      footer,
      menu,
    },
  }
}

interface Props {
  doc: any
  footer: any
  menu: any
}

const ContentPage: NextPage<Props> = (props) => {
  const { footer } = props
  return (
    <>
      <Head>
        <title>Aerosol Aliance</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
      </Head>
      <main className="relative mx-auto flex max-w-[1920px] flex-col">
        <Header slices={props.menu?.data?.slices} />
        <SliceZone
          slices={props.doc?.data?.slices}
          components={components}
        />
      </main>
      <Footer {...footer} />
    </>
  )
}

export default ContentPage
