import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import Client from '../prismicHelpers'
// @ts-ignore
import SliceZone from 'next-slicezone'
import * as Slices from '../slices'
import { Footer } from '../components/footer'
import { BurgerMenu } from '../components/burgerMenu'
import { Logo } from '../components/logo'

// @ts-ignore
const resolver = ({ sliceName }) => Slices[sliceName]

export const getStaticProps: GetStaticProps = async () => {
  const aboutUs = (await Client().getSingle('about-us', {})) || null
  const footer = (await Client().getSingle('footer', {})) || null
  const menu = (await Client().getSingle('burgerMenu', {})) || null

  return {
    props: {
      aboutUs,
      footer,
      menu,
    },
  }
}

interface Props {
  aboutUs: any
  footer: any
  menu: any
}

const Manifesto: NextPage<Props> = (props) => {
  return (
    <>
      <Head>
        <title>Aerosol Aliance</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex relative flex-col mx-auto max-w-[1920px]">
        <Logo />
        <BurgerMenu menuItems={props.menu?.data?.slices} />
        <SliceZone slices={props.aboutUs?.data?.slices} resolver={resolver} />
      </main>
      <Footer data={props.footer.data} />
    </>
  )
}

export default Manifesto
