import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import Client from '../prismicHelpers'
// @ts-ignore
import SliceZone from 'next-slicezone'
import * as Slices from '../slices'
import { Footer } from '../components/footer'
import Link from 'next/link'
import { RichText, RichTextBlock } from 'prismic-reactjs'
import { linkResolver } from '../prismicConfiguration'
import { BurgerMenu } from '../components/burgerMenu'

// @ts-ignore
const resolver = ({ sliceName }) => Slices[sliceName]

export const getStaticProps: GetStaticProps = async () => {
  const home = (await Client().getSingle('home', {})) || null
  const footer = (await Client().getSingle('footer', {})) || null
  const menu = (await Client().getSingle('burgerMenu', {})) || null

  return {
    props: {
      home,
      footer,
      menu,
    },
  }
}

interface Props {
  home: any
  footer: any
  menu: any
}

const Home: NextPage<Props> = (props) => {
  return (
    <>
      <Head>
        <title>Aerosol Aliance</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex relative flex-col mx-auto max-w-[1920px]">
        <BurgerMenu menuItems={props.menu?.data?.slices} />
        <SliceZone slices={props.home.data.slices} resolver={resolver} />
      </main>
      <Footer data={props.footer.data} />
    </>
  )
}

export default Home
