import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import Client from '../prismicHelpers'
// @ts-ignore
import SliceZone from 'next-slicezone'
import * as Slices from '../slices'

// @ts-ignore
const resolver = ({ sliceName }) => Slices[sliceName]

export const getStaticProps: GetStaticProps = async () => {
  const document = (await Client().getSingle('home', {})) || null

  return {
    props: document,
  }
}

interface Props {
  data: any
}

const Home: NextPage<Props> = (props) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="max-w-[1920px] flex flex-col mx-auto">
        {props.data.slices[0] && (
          <Slices.Herosection slice={props.data.slices[0]} />
        )}
        {props.data.slices[1] && (
          <Slices.Herosection slice={props.data.slices[1]} />
        )}
      </main>
    </>
  )
}

export default Home
