import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import Client from '../prismicHelpers'
// @ts-ignore
import SliceZone from 'next-slicezone'
import * as Slices from '../slices'
import { Footer } from '../components/footer'

// @ts-ignore
const resolver = ({ sliceName }) => Slices[sliceName]

export const getStaticProps: GetStaticProps = async () => {
  const manifesto = (await Client().getSingle('manifesto', {})) || null
  const footer = (await Client().getSingle('footer', {})) || null

  return {
    props: {
      manifesto,
      footer,
    },
  }
}

interface Props {
  manifesto: any
  footer: any
}

const Manifesto: NextPage<Props> = (props) => {
  return (
    <>
      <Head>
        <title>Aerosol Aliance</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex flex-col mx-auto max-w-[1920px]">
        <SliceZone slices={props.manifesto?.data?.slices} resolver={resolver} />
      </main>
      <Footer data={props.footer.data} />
    </>
  )
}

export default Manifesto
