import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import { Footer } from '../components/footer'
import { BurgerMenu } from '../components/burgerMenu'
import { Logo } from '../components/logo'
import { createClient } from '../prismicio'
import { Slicemachine } from '../components/slicemachine'

export const getStaticProps: GetStaticProps = async ({ previewData }) => {
  const client = createClient(previewData)

  const document = (await client.getSingle('submit-ideas', {})) || null
  const footer = (await client.getSingle('footer', {})) || null
  const menu = (await client.getSingle('burgerMenu', {})) || null

  return {
    props: {
      document,
      footer,
      menu,
    },
  }
}

interface Props {
  document: any
  footer: any
  menu: any
}

const Manifesto: NextPage<Props> = (props) => {
  return (
    <>
      <Head>
        <title>Aerosol Aliance</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex relative flex-col mx-auto max-w-[1920px]">
        <Logo />
        <BurgerMenu menuItems={props.menu?.data?.slices} />
        <Slicemachine slices={props.document?.data?.slices} />
      </main>
      <Footer data={props.footer.data} />
    </>
  )
}

export default Manifesto
